name: phone_contact_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  animations: ^2.0.7
  image_picker: ^0.8.6+1
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  cloud_firestore: ^4.4.2
  firebase_storage: ^11.0.13
  firebase_messaging: ^14.2.4
  flutter_local_notifications: ^13.0.0
  fluttertoast: ^8.2.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  pinput: ^3.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/images/